#lang info
(define collection "<project>")
(define deps '("base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("scribblings/<project>.scrbl" ())))
(define pkg-desc "Description Here")
(define version "0.0")
(define pkg-authors '(<username>))
(define compile-omit-paths '("tests"))
(define test-include-paths '("tests"))
(define clean '("compiled" "doc" "doc/<project>" "tests/compiled" "tests/private/compiled"))
